version: '3.8'

services:
  debug:
    hostname: $PWD
    build:
      context: $PWD
      args:
        - USER
        - XDG_RUNTIME_DIR
    tty: true
    stdin_open: true
    network_mode: default
    shm_size: 80g
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
              count: all
              # device_ids: ['4', '5', '6', '7']
    volumes:
      - $PWD:/workspace
      - ~/data/nnUNetV2_preprocessed_TDSC-ABUS2023_NIFTI_RemovedUnconnected:/workspace/nnUNet_preprocessed/Dataset999_DEBUG
      - ~/data/nnUNetV2_TDSC-ABUS2023_NIFTI_RemovedUnconnected:/workspace/nnUNet_raw/Dataset999_DEBUG
    environment:
      # - CUDA_VISIBLE_DEVICES=0
      - nnUNet_def_n_proc=16
